var dir_db3a54907829b36871118d03417739cd =
[
    [ "audio.c", "client_2audio_8c.html", "client_2audio_8c" ],
    [ "audio.h", "client_2audio_8h.html", "client_2audio_8h" ],
    [ "bitrate.c", "bitrate_8c.html", "bitrate_8c" ],
    [ "bitrate.h", "bitrate_8h.html", "bitrate_8h" ],
    [ "client_utils.c", "client__utils_8c.html", "client__utils_8c" ],
    [ "client_utils.h", "client__utils_8h.html", "client__utils_8h" ],
    [ "handle_server_message.c", "handle__server__message_8c.html", "handle__server__message_8c" ],
    [ "handle_server_message.h", "handle__server__message_8h.html", "handle__server__message_8h" ],
    [ "main.c", "client_2main_8c.html", "client_2main_8c" ],
    [ "native_window_utils.h", "native__window__utils_8h.html", "native__window__utils_8h" ],
    [ "native_window_utils_windows.c", "native__window__utils__windows_8c.html", "native__window__utils__windows_8c" ],
    [ "native_window_utils_x11.c", "native__window__utils__x11_8c.html", "native__window__utils__x11_8c" ],
    [ "network.c", "client_2network_8c.html", "client_2network_8c" ],
    [ "network.h", "client_2network_8h.html", "client_2network_8h" ],
    [ "ringbuffer.c", "ringbuffer_8c.html", "ringbuffer_8c" ],
    [ "ringbuffer.h", "ringbuffer_8h.html", "ringbuffer_8h" ],
    [ "sdl_event_handler.c", "sdl__event__handler_8c.html", "sdl__event__handler_8c" ],
    [ "sdl_event_handler.h", "sdl__event__handler_8h.html", "sdl__event__handler_8h" ],
    [ "sdl_utils.c", "sdl__utils_8c.html", "sdl__utils_8c" ],
    [ "sdl_utils.h", "sdl__utils_8h.html", "sdl__utils_8h" ],
    [ "sdlscreeninfo.c", "sdlscreeninfo_8c.html", "sdlscreeninfo_8c" ],
    [ "sdlscreeninfo.h", "sdlscreeninfo_8h.html", "sdlscreeninfo_8h" ],
    [ "sync_packets.c", "sync__packets_8c.html", "sync__packets_8c" ],
    [ "sync_packets.h", "sync__packets_8h.html", "sync__packets_8h" ],
    [ "video.c", "client_2video_8c.html", "client_2video_8c" ],
    [ "video.h", "client_2video_8h.html", "client_2video_8h" ]
];