var dir_db3a54907829b36871118d03417739cd =
[
    [ "audio.c", "client_2audio_8c.html", "client_2audio_8c" ],
    [ "audio.h", "client_2audio_8h.html", "client_2audio_8h" ],
    [ "client_utils.c", "client__utils_8c.html", "client__utils_8c" ],
    [ "client_utils.h", "client__utils_8h.html", "client__utils_8h" ],
    [ "handle_server_message.c", "handle__server__message_8c.html", "handle__server__message_8c" ],
    [ "handle_server_message.h", "handle__server__message_8h.html", "handle__server__message_8h" ],
    [ "main.c", "client_2main_8c.html", "client_2main_8c" ],
    [ "native_window_utils.h", "native__window__utils_8h.html", "native__window__utils_8h" ],
    [ "network.c", "client_2network_8c.html", "client_2network_8c" ],
    [ "network.h", "client_2network_8h.html", "client_2network_8h" ],
    [ "peercursor.c", "peercursor_8c.html", "peercursor_8c" ],
    [ "peercursor.h", "peercursor_8h.html", "peercursor_8h" ],
    [ "ringbuffer.c", "ringbuffer_8c.html", "ringbuffer_8c" ],
    [ "ringbuffer.h", "ringbuffer_8h.html", "ringbuffer_8h" ],
    [ "sdl_event_handler.c", "sdl__event__handler_8c.html", "sdl__event__handler_8c" ],
    [ "sdl_event_handler.h", "sdl__event__handler_8h.html", "sdl__event__handler_8h" ],
    [ "sdl_utils.c", "sdl__utils_8c.html", "sdl__utils_8c" ],
    [ "sdl_utils.h", "sdl__utils_8h.html", "sdl__utils_8h" ],
    [ "sdlscreeninfo.c", "sdlscreeninfo_8c.html", "sdlscreeninfo_8c" ],
    [ "sdlscreeninfo.h", "sdlscreeninfo_8h.html", "sdlscreeninfo_8h" ],
    [ "video.c", "client_2video_8c.html", "client_2video_8c" ],
    [ "video.h", "client_2video_8h.html", "client_2video_8h" ]
];