var searchData=
[
  ['ffmpegencoder_2006',['FFmpegEncoder',['../structFFmpegEncoder.html',1,'']]],
  ['fractalclientmessage_2007',['FractalClientMessage',['../structFractalClientMessage.html',1,'']]],
  ['fractalcursor_2008',['FractalCursor',['../structFractalCursor.html',1,'']]],
  ['fractalcursorimage_2009',['FractalCursorImage',['../structFractalCursorImage.html',1,'']]],
  ['fractalcursortypes_2010',['FractalCursorTypes',['../structFractalCursorTypes.html',1,'']]],
  ['fractaldestination_2011',['FractalDestination',['../structFractalDestination.html',1,'']]],
  ['fractaldiscoveryreplymessage_2012',['FractalDiscoveryReplyMessage',['../structFractalDiscoveryReplyMessage.html',1,'']]],
  ['fractaldiscoveryrequestmessage_2013',['FractalDiscoveryRequestMessage',['../structFractalDiscoveryRequestMessage.html',1,'']]],
  ['fractalkeyboardmessage_2014',['FractalKeyboardMessage',['../structFractalKeyboardMessage.html',1,'']]],
  ['fractalkeyboardstate_2015',['FractalKeyboardState',['../structFractalKeyboardState.html',1,'']]],
  ['fractalmousebuttonmessage_2016',['FractalMouseButtonMessage',['../structFractalMouseButtonMessage.html',1,'']]],
  ['fractalmousemotionmessage_2017',['FractalMouseMotionMessage',['../structFractalMouseMotionMessage.html',1,'']]],
  ['fractalmousewheelmessage_2018',['FractalMouseWheelMessage',['../structFractalMouseWheelMessage.html',1,'']]],
  ['fractalmultigesturemessage_2019',['FractalMultigestureMessage',['../structFractalMultigestureMessage.html',1,'']]],
  ['fractalpacket_2020',['FractalPacket',['../structFractalPacket.html',1,'']]],
  ['fractalrgbcolor_2021',['FractalRGBColor',['../structFractalRGBColor.html',1,'']]],
  ['fractalservermessage_2022',['FractalServerMessage',['../structFractalServerMessage.html',1,'']]],
  ['fractaltcprecoverymessage_2023',['FractalTCPRecoveryMessage',['../structFractalTCPRecoveryMessage.html',1,'']]],
  ['fractaltimedata_2024',['FractalTimeData',['../structFractalTimeData.html',1,'']]],
  ['fractalyuvcolor_2025',['FractalYUVColor',['../structFractalYUVColor.html',1,'']]],
  ['framedata_2026',['FrameData',['../structFrameData.html',1,'']]]
];
